# Generated by Django 3.2.18 on 2023-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230503_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
